### ISSUE TITLE
6.2.0 (pre-release) - Unhandled error loading module

### ISSUE THREAD

**Issue by scottebuchanan** [DNNCommunity/DNN.FormAndList#6]
I have upgraded Forms and List to 6.2.0 on DNN 8.0.2
When viewing the page as a guest or non-admin user, all is well.
When logged in as an administrator, which will hide the CAPTCHA and display the "Show Records" link, the form is displayed but the "Show Records" link is not (neither is the CAPTCHA, just to be clear).
Instead the bottom of the page contains the text of an error message:
`DotNetNuke.Services.Exceptions.ModuleLoadException: Unhandled Error Adding Module to ContentPane. 
---> System.ArgumentNullException: Value cannot be null. 
Parameter name: type 
at System.Activator.CreateInstance(Type type, Boolean nonPublic) 
at System.Activator.CreateInstance(Type type) 
at DotNetNuke.Modules.UserDefinedTable.DataType.get_DataTypes() 
at DotNetNuke.Modules.UserDefinedTable.DataType.ByName(String dataTypeName) 
at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm() 
at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e) 
at System.Web.UI.Control.InitRecursive(Control namingContainer) 
at System.Web.UI.Control.AddedControl(Control control, Int32 index) 
at DotNetNuke.Modules.UserDefinedTable.Default.LoadControlByKey(String controlKey) 
at System.Web.UI.Control.InitRecursive(Control namingContainer) 
at System.Web.UI.Control.AddedControl(Control control, Int32 index) 
at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content) 
at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls() 
at System.Web.UI.Control.EnsureChildControls() 
at DotNetNuke.UI.Containers.Container.get_ModuleControl() 
at DotNetNuke.UI.Containers.Container.ProcessModule() 
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
 --- End of inner exception stack trace --- 
`

**Comment by DotNetNuclear** [comment]
Scott, would you be able to export the [UserDefinedFields] table for the ModuleId of your form so I can reproduce this issue?

**Comment by scottebuchanan** [comment]
I'm sorry, but I do not currently have a DNN 8.x instance.  I will build a test site again, but likely not until spring 2017.

**Comment by brentil** [comment]
We're also getting the same error on 3 separate DNN 8.0.4 installations (2 dev and 1 live) with FnL 6.2.0 installed.  Talking to the developers they typically see it when first coming to the page but then any followup visit doesn't show the error.  We've seen it from logged in and not logged in users.  I've attached the output from the userDefinedFields table for the specific module ID.


[FnL.txt](https://github.com/DNNCommunity/DNN.FormAndList/files/790379/FnL.txt)

**Comment by JoeAucoin** [comment]
Seeing same error on DNN 9.1. Multiple sites on different servers. IIS 8 and IIS 7

**Comment by scottebuchanan** [comment]
I have created a QA site, where I updated the site to DNN 9.1.0.  With the current Form and List 6.1.0, the page behaves well for both guest, non-admin and admin users.  The only difference from DNN 7.4.2 is that the "Show Records" link is no longer shown to admin users - instead I had to enter edit page mode.

I then updated the module to 6.2.0.  My first load of the page (as Host account) encountered "A critical error has occurred. Please check the Event Viewer for further details." I found three exceptions in the Admin Logs (added below).

After logout, I was able to access the page as guest, admin and host without error.

I restarted IIS, and as guest, navigated to the page and received the same critical error message, and found three more exceptions in the Admin Logs.

I've attached the relevant contents of [UserDefinedFields] and [UserDefinedFieldSettings].
[FormAndList-UserDefined-FCG.txt](https://github.com/DNNCommunity/DNN.FormAndList/files/1038967/FormAndList-UserDefined-FCG.txt)


Here are the three related exceptions in the Admin Logs (in order listed)
`05/30/2017 11:19:40 - Page Load Exception
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:60aaacd8-1419-45bd-91fe-2eee93c89d8c
AssemblyVersion:9.1.0
PortalId:0
UserId:-1
TabId:108
RawUrl:/ContactUs.aspx
Referrer:http://new.frankcohengroup.com/Home.aspx
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
ExceptionHash:cT14CW+BIl32yd7R9ADLRZ4kdao=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
at DotNetNuke.UI.Containers.ActionCommandButton.get_ModuleAction() 
at DotNetNuke.UI.Containers.ActionCommandButton.OnPreRender(EventArgs e) 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Control.PreRenderRecursiveInternal() 
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: FCG-SQL4
`

`05/30/2017 11:19:37 - General Exception
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:ad57ec54-a17f-471b-8cca-da8cd73762ba
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:QcvoAsAEPBMODM4xuO+gA0CW2Sc=
Message:Unhandled Error Adding Module to ContentPane.
StackTrace:
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module) at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
InnerMessage:Value cannot be null. Parameter name: type
InnerStackTrace:
at System.Activator.CreateInstance(Type type, Boolean nonPublic) 
at System.Activator.CreateInstance(Type type) 
at DotNetNuke.Modules.UserDefinedTable.DataType.get_DataTypes() 
at DotNetNuke.Modules.UserDefinedTable.DataType.ByName(String dataTypeName) 
at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm() 
at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e) 
at System.Web.UI.Control.InitRecursive(Control namingContainer) 
at System.Web.UI.Control.AddedControl(Control control, Int32 index) 
at DotNetNuke.Modules.UserDefinedTable.Default.LoadControlByKey(String controlKey) 
at System.Web.UI.Control.InitRecursive(Control namingContainer) 
at System.Web.UI.Control.AddedControl(Control control, Int32 index) 
at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content) 
at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls() 
at System.Web.UI.Control.EnsureChildControls() 
at DotNetNuke.UI.Containers.Container.get_ModuleControl() 
at DotNetNuke.UI.Containers.Container.ProcessModule() 
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
Source:DotNetNuke
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: FCG-SQL4
`

`05/30/2017 11:19:37 - General Exception
General Exception
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:7ddf77b5-7262-4b15-9bae-451ff5db78d2
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:NkfiPz/XnmrlbGW1NeWEGPAJyGY=
Message:Value cannot be null. Parameter name: type
StackTrace:
at System.Activator.CreateInstance(Type type, Boolean nonPublic) 
at System.Activator.CreateInstance(Type type) 
at DotNetNuke.Modules.UserDefinedTable.DataType.get_DataTypes() 
at DotNetNuke.Modules.UserDefinedTable.DataType.ByName(String dataTypeName) 
at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm() 
at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e) 
at System.Web.UI.Control.InitRecursive(Control namingContainer) 
at System.Web.UI.Control.AddedControl(Control control, Int32 index) 
at DotNetNuke.Modules.UserDefinedTable.Default.LoadControlByKey(String controlKey) 
at System.Web.UI.Control.InitRecursive(Control namingContainer) 
at System.Web.UI.Control.AddedControl(Control control, Int32 index) 
at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content) 
at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls() 
at System.Web.UI.Control.EnsureChildControls() 
at DotNetNuke.UI.Containers.Container.get_ModuleControl() 
at DotNetNuke.UI.Containers.Container.ProcessModule() 
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: FCG-SQL4
`

**Comment by brentil** [comment]
We've also upgraded our development environments to 9.1.0 and we continue to experience this same issue.

**Comment by SCullman** [comment]
![image](https://user-images.githubusercontent.com/5693190/41192103-8206ec04-6bf9-11e8-86b6-f7a8e028bcb0.png)
FIXED, tested in DNN9.2

**Comment by valadas** [comment]
@EPTamminga , this one too is fixed.
