### ISSUE TITLE
Source seems to be incorrect

### ISSUE THREAD

**Issue by jd8** [DNNCommunity/DNN.FormAndList#8]
Can you repost the source for version 6.02?  The Source in Source code (zip) doesn't appear to be correct for version 8. It is reference the Telerik datepicker which no longer exists in 8. This is apparent when you test the module and Add a record.

The Source in FormAndList_06.02.00_Source.zip is missing a lot of files.

**Comment by EPTamminga** [comment]
@jd8 Have you tried to fork/clone the repo for the complete project source? Or the (by GitHub) automatically created source code.zip? 
It might be that the person who created the 6.02 sources .zip did that manually and forgot items. The repo itself should be complete, however.

**Comment by jd8** [comment]
I tried the source code.zip and I also downloaded the repository.  The Add Record feature errors with 

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:f5a1ac48-253b-41c1-a336-a482cd04d350

AssemblyVersion:8.3.0

PortalId:0

Referrer:http://localhost/Default.aspx?tabid=442&error=Could+not+load+type+%27DotNetNuke.Web.UI.WebControls.DnnDatePicker%27+from+assembly+%27DotNetNuke.Web%2c+Version%3d8.0.0.809%2c+Culture%3dneutral%2c+PublicKeyToken%3dnull%27.

UserAgent:Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

ExceptionHash:5ItKUqLchdGZafZukXgAfA==

Message:Could not load type 'DotNetNuke.Web.UI.WebControls.DnnDatePicker' from assembly 'DotNetNuke.Web, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null'.

StackTrace:



InnerMessage:Could not load type 'DotNetNuke.Web.UI.WebControls.DnnDatePicker' from assembly 'DotNetNuke.Web, Version=8.0.0.809, Culture=neutral, PublicKeyToken=null'.

InnerStackTrace:
   at DotNetNuke.Modules.UserDefinedTable.DataTypes.EditDate.EditDate_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildCssForm(IEnumerable`1 editForm)
   at DotNetNuke.Modules.UserDefinedTable.EditForm.BuildEditForm()
   at DotNetNuke.Modules.UserDefinedTable.EditForm.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  
If I use the Install version instead, this feature works fine.  However, I need to turn off certain menu items for not Admin users, so I cannot use the Install version.

**Comment by jd8** [comment]
This error was caused by a bad reference I had to DotNetNuke.Web.dll. My project found the 6.25 version of this file instead of the 8.3 version.  I fixed my reference and  I am able to work with the files in DNN 8.3.   Thanks for your assistance.

**Comment by EPTamminga** [comment]
Good to read that you have solved it yourself (based upon your own doings...).
